name: 'Auto Assign'
#on: pull_request
on:
  push:
    paths:
      - '.github/**'

env:
  DOCKER_PAT: ${{ secrets.DOCKER_PAT }}

jobs:
  build:
    runs-on: ubuntu-18.04
    timeout-minutes: 20

    services:
      elasticsearch:
        image: tradeling/base-docker-image-es:latest-develop
        credentials:
          username: vamshisiddarth1
          password: ${{ secrets.DOCKER_PAT }}
        ports:
          - 9200:9200
        options: -e="discovery.type=single-node"
        
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 30
          persist-credentials: false

      - name: General
        run: |
          # comment
          echo ${{ secrets.DOCKER_PAT }}
